name: deploying myapp flask app to a KinD cluster

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  Registry: ghcr.io
  ImageRepo: memor24/myapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
     # - name: set up Docker Buildx # optimizes the build process by caching and parallelizing builds
     #  uses: docker/setup-buildx-action@v1

      - name: login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.Registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
       # run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u memo24 --password-stdin

      - name: build and push Docker image
        run: |
          docker build -t myapp:latest . && \
          docker tag myapp:latest ${{ env.Registry }}/${{ env.ImageRepo }}/myapp:latest && \
          docker push ${{ env.Registry }}/${{ env.ImageRepo }}/myapp:latest

      - name: install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: create KinD cluster
        run: kind create cluster --name myapp-cluster
        
      - name: install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name : create regcred kubernetes secret for kubectl acccess to ghcr
        run: |
          kubectl create secret docker-registry regcred \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GITHUB_TOKEN }} \
          --docker-email=${{ github.actor }}@sth.co \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: deploy the Helm chart
        run: |
          helm upgrade --install myapp ./helm/myapp \
          --set image.repository=ghcr.io/${{ github.repository }}/myapp \ 
          --set image.tag=latest \
          --set image.PullSecrets=regcred

