name: deploying myapp flask app to a KIND cluster

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  Registry: ghcr.io
  ImageName: memor24/myapp 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.Registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
       # run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u memo24 --password-stdin

      - name: build Docker image
        run: docker build -t myapp:latest .

      - name: tag docker image
        run: docker tag myapp:latest ghcr.io/${{ env.ImageName }}/myapp:latest

      - name: push Docker image
        run: docker push ghcr.io/${{ env.ImageName }}/myapp:latest

      - name: setup KinD cluster
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster --name myapp-cluster
        
      - name: install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: install myapp Helm chart
        run: helm install myapp ./myapp-chart

